// Data loader utility for static API data
// This module loads data from JSON files generated by the fetch-data script

import recipesData from "./recipes.json";
import categoriesData from "./categories.json";

import type { Recipe, Category } from "./api-types";
import { recipeNameToSlug, recipeSlugToSearchTerm } from "../utils/slugify";

interface RecipeSearchIndexEntry {
  recipe: Recipe;
  searchableText: string;
}

const normalizeSearchText = (value: string): string =>
  value.toLowerCase().replace(/\s+/g, " ").trim();

const recipeSearchIndex: RecipeSearchIndexEntry[] = (recipesData as Recipe[]).map((recipe) => {
  const searchParts = [
    recipe.name,
    recipe.description,
    recipe.ingredients,
    recipe.instructions,
    recipe.recipeCategory?.name,
    recipe.authorNM,
    recipe.seO_Keywords,
  ].filter(Boolean);

  return {
    recipe,
    searchableText: normalizeSearchText(searchParts.join(" ")),
  };
});

/**
 * Normalize slug for comparison (handle edge cases with special characters)
 */
function normalizeSlugForComparison(slug: string): string {
  return slug
    .toLowerCase()
    .replace(/--+/g, "-") // Multiple hyphens → single hyphen
    .replace(/[()]/g, "") // Remove parentheses
    .replace(/:/g, "") // Remove colons
    .replace(/^-|-$/g, ""); // Trim leading/trailing hyphens
}

/**
 * Check if we have fetched data available
 */
export function hasApiData(): boolean {
  try {
    return Array.isArray(recipesData) && recipesData.length > 0;
  } catch {
    return false;
  }
}

/**
 * Get all recipes
 */
export function getRecipes(): Recipe[] {
  return recipesData as Recipe[];
}

/**
 * Get recipe by ID
 */
export function getRecipeById(id: number): Recipe | undefined {
  const recipes = getRecipes();
  return recipes.find((recipe) => recipe.id === id);
}

/**
 * Get recipe by URL slug from the API's recipeURL field
 */
export function getRecipeBySlug(slug: string): Recipe | undefined {
  const recipes = getRecipes();
  const normalizedInputSlug = normalizeSlugForComparison(slug);

  // First try exact match with API's recipeURL (remove leading /recipe/ if present)
  const targetPath = slug.startsWith("recipe/")
    ? `/${slug}`
    : `/recipe/${slug}`;
  let recipe = recipes.find((recipe) => recipe.recipeURL === targetPath);

  // If no exact match with recipeURL, try generated slug from name
  if (!recipe) {
    recipe = recipes.find((recipe) => {
      const recipeSlug = recipeNameToSlug(recipe.name);
      return normalizeSlugForComparison(recipeSlug) === normalizedInputSlug;
    });
  }

  // If no match with normalized comparison, try API recipeURL normalization
  if (!recipe) {
    recipe = recipes.find((recipe) => {
      if (recipe.recipeURL) {
        const match = recipe.recipeURL.match(/\/recipe\/(.+)$/);
        if (match && match[1]) {
          return normalizeSlugForComparison(match[1]) === normalizedInputSlug;
        }
      }
      return false;
    });
  }

  // If still no exact match, try fuzzy search
  if (!recipe) {
    const searchTerm = recipeSlugToSearchTerm(slug);
    recipe = recipes.find((recipe) =>
      recipe.name.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }

  return recipe;
}

/**
 * Generate SEO-friendly slug for a recipe using API's recipeURL if available
 */
export function getRecipeSlug(recipe: Recipe): string {
  // Use the API's recipeURL if available, otherwise fall back to generated slug
  if (recipe.recipeURL) {
    // Extract the slug part from /recipe/slug-name
    const match = recipe.recipeURL.match(/\/recipe\/(.+)$/);
    if (match && match[1]) {
      return match[1];
    }
  }
  // Fallback to generated slug from name
  return recipeNameToSlug(recipe.name);
}

/**
 * Get recipe URL path using API's recipeURL if available
 */
export function getRecipeUrl(recipe: Recipe): string {
  // Use the API's recipeURL if available, otherwise construct from slug
  if (recipe.recipeURL && recipe.recipeURL.startsWith("/recipe/")) {
    return recipe.recipeURL;
  }
  // Fallback to constructed URL
  return `/recipe/${getRecipeSlug(recipe)}`;
}

/**
 * Get recipes by category ID
 */
export function getRecipesByCategory(categoryId: number): Recipe[] {
  const recipes = getRecipes();
  return recipes.filter((recipe) => recipe.recipeCategoryID === categoryId);
}

/**
 * Get all categories
 */
export function getCategories(): Category[] {
  return categoriesData as Category[];
}

/**
 * Get category by ID
 */
export function getCategoryById(id: number): Category | undefined {
  const categories = getCategories();
  return categories.find((category) => category.id === id);
}

/**
 * Get category by URL slug
 */
export function getCategoryBySlug(slug: string): Category | undefined {
  const categories = getCategories();
  return categories.find((category) => category.url === slug);
}

/**
 * Search recipes by name, description, or ingredients
 */
export function searchRecipes(query: string): Recipe[] {
  const normalizedQuery = normalizeSearchText(query);
  if (!normalizedQuery) return [];

  const queryTokens = normalizedQuery.split(" ").filter(Boolean);
  if (queryTokens.length === 0) return [];

  return recipeSearchIndex
    .map(({ recipe, searchableText }) => {
      let score = 0;
      const recipeName = normalizeSearchText(recipe.name || "");
      const recipeCategory = normalizeSearchText(recipe.recipeCategory?.name || "");

      for (const token of queryTokens) {
        if (recipeName.startsWith(token)) score += 12;
        if (recipeName.includes(token)) score += 8;
        if (recipeCategory.includes(token)) score += 4;
        if (searchableText.includes(token)) score += 2;
      }

      if (recipeName.includes(normalizedQuery)) {
        score += 24;
      } else if (searchableText.includes(normalizedQuery)) {
        score += 8;
      }

      return { recipe, score };
    })
    .filter((entry) => entry.score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return (b.recipe.averageRating || 0) - (a.recipe.averageRating || 0);
    })
    .map((entry) => entry.recipe);
}

/**
 * Get featured recipes (highest rated or most recent)
 */
export function getFeaturedRecipes(limit: number = 6): Recipe[] {
  const recipes = getRecipes();

  // Sort by average rating (descending) and then by creation date (most recent)
  return [...recipes]
    .sort((a, b) => {
      const ratingA = a.averageRating || 0;
      const ratingB = b.averageRating || 0;

      if (ratingA !== ratingB) {
        return ratingB - ratingA;
      }

      // Secondary sort by creation date
      const dateA = new Date(a.createdDT || 0);
      const dateB = new Date(b.createdDT || 0);
      return dateB.getTime() - dateA.getTime();
    })
    .slice(0, limit);
}

/**
 * Get recipe statistics
 */
export function getRecipeStats() {
  const recipes = getRecipes();
  const categories = getCategories();

  const stats = {
    totalRecipes: recipes.length,
    totalCategories: categories.length,
    averageRating: 0,
    recipesByCategory: {} as Record<string, number>,
    recentRecipes: 0,
  };

  // Calculate average rating
  const ratedRecipes = recipes.filter((r) => r.averageRating);
  if (ratedRecipes.length > 0) {
    stats.averageRating =
      ratedRecipes.reduce((sum, r) => sum + (r.averageRating || 0), 0) /
      ratedRecipes.length;
  }

  // Count recipes by category
  categories.forEach((category) => {
    const count = recipes.filter(
      (r) => r.recipeCategoryID === category.id
    ).length;
    stats.recipesByCategory[category.name] = count;
  });

  // Count recent recipes (last 30 days)
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  stats.recentRecipes = recipes.filter((r) => {
    const createdDate = new Date(r.createdDT || 0);
    return createdDate > thirtyDaysAgo;
  }).length;

  return stats;
}

/**
 * Get data freshness information
 */
export function getDataMetadata() {
  return {
    fetchedAt: "Unknown",
    totalRecipes: getRecipes().length,
    totalCategories: getCategories().length,
    totalWebsites: 0,
  };
}
